__main__ 2023-05-27 15:13:26,236 INFO -----------------------------------------------------
code_completion_lib.parse_notebooks 2023-05-27 15:21:46,386 ERROR Exception
Traceback (most recent call last):
  File "D:\sasha\code_completion\code_completion_lib\parse_notebooks.py", line 103, in parse
    full_code += "\n" + code
TypeError: can only concatenate str (not "NoneType") to str
code_completion_lib.parse_notebooks 2023-05-27 15:24:39,803 INFO 0.0027375509868871307% failed in parse func
code_completion_lib.parse_notebooks 2023-05-27 15:24:39,803 INFO 10.383530893262886% passed in parse func
__main__ 2023-05-27 15:32:04,304 INFO -----------------------------------------------------
code_completion_lib.methods.find_methods_in_code 2023-05-27 15:32:26,802 INFO size = small
code_completion_lib.imports.imports 2023-05-27 15:33:04,035 INFO Find methods ended.
code_completion_lib.code_completion 2023-05-27 15:34:19,020 ERROR Exception
Traceback (most recent call last):
  File "C:\Users\mosas\AppData\Local\Temp\ipykernel_16124\1635884698.py", line 43, in <module>
    acc_top3 = top_3(y_true, y_pred_top3)
NameError: name 'top_3' is not defined
code_completion_lib.code_completion 2023-05-27 15:34:19,059 ERROR Exception
Traceback (most recent call last):
  File "C:\Users\mosas\AppData\Local\Temp\ipykernel_16124\1635884698.py", line 43, in <module>
    acc_top3 = top_3(y_true, y_pred_top3)
NameError: name 'top_3' is not defined
code_completion_lib.code_completion 2023-05-27 15:34:19,095 ERROR Exception
Traceback (most recent call last):
  File "C:\Users\mosas\AppData\Local\Temp\ipykernel_16124\1635884698.py", line 43, in <module>
    acc_top3 = top_3(y_true, y_pred_top3)
NameError: name 'top_3' is not defined
code_completion_lib.code_completion 2023-05-27 15:34:19,135 ERROR Exception
Traceback (most recent call last):
  File "C:\Users\mosas\AppData\Local\Temp\ipykernel_16124\1635884698.py", line 43, in <module>
    acc_top3 = top_3(y_true, y_pred_top3)
NameError: name 'top_3' is not defined
code_completion_lib.code_completion 2023-05-27 15:34:19,177 ERROR Exception
Traceback (most recent call last):
  File "C:\Users\mosas\AppData\Local\Temp\ipykernel_16124\1635884698.py", line 43, in <module>
    acc_top3 = top_3(y_true, y_pred_top3)
NameError: name 'top_3' is not defined
code_completion_lib.methods.find_methods_in_code 2023-05-27 15:35:16,785 INFO size = small
code_completion_lib.imports.imports 2023-05-27 15:35:53,248 INFO Find methods ended.
__main__ 2023-05-27 16:09:57,080 INFO -----------------------------------------------------
code_completion_lib.methods.find_methods_in_code 2023-05-27 16:09:57,112 INFO size = small
__main__ 2023-05-27 20:22:50,586 INFO -----------------------------------------------------
